<h2>Agregar departamento</h2>

<form action="<?php echo APP_URL."departamentos/add"; ?>" method="POST">
		
		<p>Departamento: <input type="text" name="nombre"></p>
		<p>Responsable:
		    <select name="responsables_id" class="form-control"> 
		        <option value="">Selecciona ...</option>
		        <?php foreach ($this->responsables as $responsable): ?>
		        <option value="<?php echo $responsable["id"]; ?>"><?php echo $responsable["nombre"]; ?></option>
		        <?php endforeach; ?>
		    </select>
        </p>
		<p><input type="submit"></p>