<h2>Agregar usuario</h2>

<form action="<?php echo APP_URL."usuarios/add"; ?>" method="POST">
		<p>Nombre: <input type="text" name="nombre"></p>
		<p>Apellidos: <input type="text" name="apellido"></p>
		<p>Usuario: <input type="text" name="usuario"></p>
		<p>Password: <input type="password" name="password"></p>
		<p>Status: <input type="text" name="status"></p>
		<p>Lugar: <input type="text" name="lugar"></p>
		<p><input type="submit"></p>