<h2>Listado de categorias</h2>
<a href="<?php echo APP_URL."categorias/add"; ?>">Agregar categorias</a>
<table border="1">
	<tr>
		<th>ID</th>
		<th>Nombre</th>
	</tr>
	<?php foreach ($this->categorias as $categoria): ?>
	<tr>
		<td><?php echo $categoria["id"]; ?></td>
		<td><?php echo $categoria["nombre"]; ?></td>
		<td><?php ?>
			<a href="<?php echo APP_URL."categorias/edit/".$categoria["id"]; ?>">Editar</a>
			<a href="<?php echo APP_URL."categorias/delete/".$categoria["id"]; ?>">Eliminar</a>
		</td>
	</tr>	
	<?php endforeach; ?>
</table>