<h2>Listado de equipos</h2>
<a href="<?php echo APP_URL."equipos/add"; ?>">Agregar equipo</a>
<table border="1">
	<tr>
		<th>Id</th>
		<th>Equipo</th>
	</tr>
	<?php foreach ($this->equipos as $equipo): ?>
	<tr>
		<td><?php echo $equipo["id"]; ?></td>
		<td><?php echo $equipo["nombre"]; ?></td>
		<td><?php ?>
			<a href="<?php echo APP_URL."equipos/edit/".$equipo["id"]; ?>">Editar</a>
			<a href="<?php echo APP_URL."equipos/delete/".$equipo["id"]; ?>">Eliminar</a>
		</td>
	</tr>	
	<?php endforeach; ?>
</table>