<h2>Agregar tarea</h2>

<form action="<?php echo APP_URL."tareas/add"; ?>" method="POST">
		<p>Nombre: <input type="text" name="nombre" class="form-control"></p>
		<p>Categoria:
		    <select name="categoria_id" class="form-control"> 
		        <option value="">Selecciona ...</option>
		        <?php foreach ($this->categorias as $categoria): ?>
		        <option value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["nombre"]; ?></option>
		        <?php endforeach; ?>
		    </select>
        </p>
		<p>Fecha: <input type="text" name="fecha" class="form-control"></p>
		<p>Prioridad: <input type="text" name="prioridad" class="form-control"></p>
		<p>Estatus: <input type="text" name="status" class="form-control"></p>
		<p><input type="submit"></p>