<h2>Listado de marcas</h2>
<a href="<?php echo APP_URL."marcas/add"; ?>">Agregar marca</a>
<table border="1">
	<tr>
		<th>Id</th>
		<th>marca</th>
	</tr>
	<?php foreach ($this->marcas as $marca): ?>
	<tr>
		<td><?php echo $marca["id"]; ?></td>
		<td><?php echo $marca["nombre"]; ?></td>
		<td><?php ?>
			<a href="<?php echo APP_URL."marcas/edit/".$marca["id"]; ?>">Editar</a>
			<a href="<?php echo APP_URL."marcas/delete/".$marca["id"]; ?>">Eliminar</a>
		</td>
	</tr>	
	<?php endforeach; ?>
</table>